kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv
  namespace: n8n-development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      PersistentVolumeClaim: 50Gi
