apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maseko-lucky-9/n8n-self-hosting.git
    targetRevision: HEAD
    path: helm/n8n-application
    helm:
      valueFiles:
        - values-local.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n-local
  syncPolicy:
    automated:          # LOCAL: Auto-sync for rapid iteration
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
