{{- if .Values.externalSecrets.enabled }}
{{- $saName := .Values.externalSecrets.vault.auth.serviceAccount | default "external-secrets" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-application.labels" . | nindent 4 }}
    app.kubernetes.io/component: vault-integration
automountServiceAccountToken: true
{{- end }}
