apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting
  namespace: n8n-development
  kubernetes.io/ingress.class: kong
config:
  minute: 100
  hour: 1000
  policy: local
plugin: rate-limiting