apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n-application.fullname" . }}-config
  namespace: {{ .Values.namespace | default "n8n-development" }}
  labels:
    {{- include "n8n-application.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n
data:
  N8N_HOST: {{ .Values.n8n.env.N8N_HOST | quote }}
  N8N_PORT: {{ .Values.n8n.env.N8N_PORT | quote }}
  N8N_PROTOCOL: {{ .Values.n8n.env.N8N_PROTOCOL | quote }}
  WEBHOOK_URL: {{ .Values.n8n.env.WEBHOOK_URL | quote }}
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_HOST: {{ include "n8n-application.fullname" . }}-postgresql
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_DATABASE: {{ .Values.postgresql.auth.database | quote }}
  DB_POSTGRESDB_USER: {{ .Values.postgresql.auth.username | quote }}
