apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n-application.fullname" . }}-n8n
  namespace: {{ .Values.namespace | default "n8n-development" }}
  labels:
    {{- include "n8n-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "n8n-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "n8n-application.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: n8n
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        ports:
        - name: http
          containerPort: 5678
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: N8N_HOST
          value: "{{ .Values.n8n.host }}"
        - name: N8N_PORT
          value: "5678"
        - name: N8N_PROTOCOL
          value: "{{ .Values.n8n.protocol }}"
        - name: DB_TYPE
          value: "{{ .Values.database.type }}"
        - name: DB_POSTGRESDB_HOST
          valueFrom:
            secretKeyRef:
              name: {{ include "n8n-application.fullname" . }}-db-secret
              key: host
        - name: DB_POSTGRESDB_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "n8n-application.fullname" . }}-db-secret
              key: username
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "n8n-application.fullname" . }}-db-secret
              key: password
        - name: DB_POSTGRESDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "n8n-application.fullname" . }}-db-secret
              key: database
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: {{ include "n8n-application.fullname" . }}-n8n-pvc
      - name: tmp
        emptyDir: {}
