kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "n8n-application.fullname" . }}-postgres-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgres.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | default "10Gi" }}
