{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "n8n-application.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default "n8n-development" }}
  labels:
    {{- include "n8n-application.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "n8n-application.fullname" . }}