{{- if .Values.queue.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n-application.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-application.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "n8n-application.name" . | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis
{{- end }}
