{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "n8n-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n-application.labels" . | nindent 4 }}
    {{- with .Values.monitoring.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      service: n8n
  endpoints:
    - port: "5678"
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval | default "30s" }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout | default "10s" }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
